#!/usr/bin/env bash
# 06_configure_consumer_skill.sh — write .kb-config into the sibling
# `knowledge-base/` consumer skill so its scripts can talk to this KB instance.
#
# Looks for a sibling skill at $SKILL_ROOT/../knowledge-base (the convention when
# both build-kb and knowledge-base ship in the same plugin). Override the
# location with --target <path> if the skill lives elsewhere.

set -euo pipefail
[[ -f "${HOME}/.kb-bootstrap.env" ]] && source "${HOME}/.kb-bootstrap.env"
: "${KB_NAME:?}" "${WORKERS_SUBDOMAIN:?}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILL_ROOT="$(dirname "$SCRIPT_DIR")"
ARTIFACTS="$SKILL_ROOT/generated/knowledge-base"

TARGET=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --target) TARGET="$2"; shift 2 ;;
    *)        echo "Usage: $0 [--target <path-to-knowledge-base-skill>]" >&2; exit 64 ;;
  esac
done

# Default target: sibling skill folder in the same plugin.
if [[ -z "$TARGET" ]]; then
  TARGET="$(dirname "$SKILL_ROOT")/knowledge-base"
fi

[[ ! -f "$ARTIFACTS/.token" ]] && { echo "missing $ARTIFACTS/.token — run 04_deploy_search_worker.sh first" >&2; exit 1; }
[[ ! -f "$ARTIFACTS/.url" ]]   && { echo "missing $ARTIFACTS/.url — run 04_deploy_search_worker.sh first" >&2; exit 1; }
[[ ! -d "$TARGET" ]]           && { echo "consumer skill folder not found at: $TARGET" >&2; echo "Pass --target if it lives elsewhere." >&2; exit 1; }

CONSUMER_TOKEN=$(cat "$ARTIFACTS/.token")
WORKER_URL=$(cat "$ARTIFACTS/.url")
WRITE_TOKEN=$(cat "$ARTIFACTS/.write-token" 2>/dev/null || echo "")

CFG="$TARGET/.kb-config"
echo "→ Writing $CFG"

cat > "$CFG" <<EOF
# KB instance config — sourced by every script in scripts/.
# Generated by build-kb's bootstrap; rotate values here as needed.
KB_WORKER_URL="$WORKER_URL"
KB_TOKEN="$CONSUMER_TOKEN"
KB_WRITE_TOKEN="$WRITE_TOKEN"
EOF
chmod 600 "$CFG"

# Ensure scripts are executable
chmod +x "$TARGET"/scripts/*.sh 2>/dev/null || true

echo "  ✓ .kb-config written (chmod 600)"
echo "  ✓ Worker URL: $WORKER_URL"
echo "  ✓ Read token: ${CONSUMER_TOKEN:0:14}…"
[[ -n "$WRITE_TOKEN" ]] && echo "  ✓ Write token: ${WRITE_TOKEN:0:18}…" || echo "  ⚠ No write token (read-only deploy)"
echo
echo "The consumer skill at $TARGET is now active."
